import { poppins } from "@/utils/fonts";
// import "./auth.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Auth</title>
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
