// import '../styles/main.scss'
import { ToastContainer } from "react-toastify";
import { poppins } from "@/utils/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
      </head>
      <body className={poppins.className + " scrollbar"}>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
