// import '../styles/main.scss'
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
      </head>
      <body className={poppins.className + " scrollbar"}>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
